image:
- Visual Studio 2019
- macOS
- Ubuntu


skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
- pip install briefcase
- pip install pillow

build_script:
- briefcase create
- briefcase build

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a gym-windows.zip %CD%\dist\*.msi

  artifacts:
  - path: gym-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf gym-macos.tar.gz -C dist gym.app

  artifacts:
  - path: gym-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf gym-linux.tar.gz -C dist counter

  artifacts:
  - path: gym-linux.tar.gz
